distributionUrl=https://java.repo.sfa.se/repository/java-all/org/apache/maven/apache-maven/3.9.11/apache-maven-3.9.11-bin.zip
wrapperUrl=https://java.repo.sfa.se/repository/java-all/org/apache/maven/wrapper/maven-wrapper/3.3.4/maven-wrapper-3.3.4.jar
